### ISSUE TITLE
Incorrect GameStageHelper usage. 

### ISSUE THREAD

**Issue by Darkhax** [Mrbysco/TimeStages#3]
Hey, was looking at some of the code in your mod. Could you please use the correct methods in the GameStageHelper class for adding/removing stages? The way you're currently doing things doesn't fire any of the events that should normally be fired. In general accessing the stage data object directly should be avoided. 

(Also package names ;p and methods should also be camelCase)

**Comment by Mrbysco** [comment]
Working on it 😉

**Comment by Mrbysco** [comment]
See https://github.com/Mrbysco/TimeStages/commit/8ef5d2922194404f727d341b17c781ade6bc599f

**Comment by Mrbysco** [comment]
1.2.1 has been released.
