### ISSUE TITLE
[Suggestion]: Message Configuration

### ISSUE THREAD

**Issue by Kasualix** [Mrbysco/TimeStages#6]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

![image](https://user-images.githubusercontent.com/110756250/199971823-f413cdef-8221-4619-854f-b8418f7337c1.png)
Message(s) will be sent to player when timers end.
But I don't want them to be sent.
It would be nice if you can make this send configurable in Minecraft 1.16.5

**Comment by Mrbysco** [comment]
A silent version has been implemented as of https://github.com/Mrbysco/TimeStages/commit/e5981a56b07a797ad63eb2b7d3a0f3d05d31e560
