### ISSUE TITLE
[Bug]: Invalid script..?

### ISSUE THREAD

**Issue by CaptianCruz** [Mrbysco/TimeStages#7]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.7

### Minecraft version

1.19.2

### Mod version

2.1.0

### Java version

17.0.8

### Issue Description

I keep getting errors from lines with Time Stages:
Cannot evaluete a package as expression

Even if I copy/paste exaples from Pages section, I still get the same error. So far it only happens with Time Stages

### Additional Information

https://pastebin.com/zjv9k3jy

**Comment by Mrbysco** [comment]
Try the code from the github readme. I probably forgot to update the curseforge pages
https://github.com/Mrbysco/TimeStages/blob/1.20.1/README.md

**Comment by CaptianCruz** [comment]
Everything works flawlessly! Thank you!
